// Content assembler. The KB distillers return HTML with entity-escaped tags
// (some singly-escaped like &lt;p&gt;, some doubly-escaped like &amp;lt;p&amp;gt;).
// We unescape to a fixed point so both normalize to real tags, then emit the
// site's data modules. Safe to re-run.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');

function unescapeOnce(s) {
  return s
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&amp;/g, '&');
}
// apply until stable (handles double-escaping); cap iterations
function unescapeHtml(s) {
  let prev = s, next = unescapeOnce(s), i = 0;
  while (next !== prev && i < 4) { prev = next; next = unescapeOnce(next); i++; }
  return next;
}
// some drafts used raw blank lines instead of <br>/<p> for paragraph breaks
function normalizeBreaks(s) {
  return s.replace(/\s*\n\s*\n\s*/g, '<br><br>').replace(/\n/g, ' ');
}
function walk(v) {
  if (typeof v === 'string') return normalizeBreaks(unescapeHtml(v));
  if (Array.isArray(v)) return v.map(walk);
  if (v && typeof v === 'object') {
    const o = {};
    for (const k of Object.keys(v)) o[k] = walk(v[k]);
    return o;
  }
  return v;
}
const readJson = (p) => JSON.parse(readFileSync(join(here, p), 'utf8'));
function emit(rel, name, value, note) {
  const out =
    `// AUTO-GENERATED by scripts/build-content.mjs — do not hand-edit.\n` +
    `// ${note}\n` +
    `export const ${name} = ${JSON.stringify(value, null, 2)};\n`;
  writeFileSync(join(root, rel), out);
}

// The how-to branch was RETIRED 2026-07-29. Its output, src/data/howtos.js, is now
// the hand-maintained src/data/lessons.js — the generator existed to unescape HTML
// from the KB distillers, a job long finished, and a one-way importer made real
// editorial work (merging two lessons, splitting one) impossible. The three
// howto-raw*.json inputs are deleted; this script still builds glossary + resources.

// ---- glossary ----
const glossary = walk(readJson('glossary-raw.json')).terms;
emit('src/data/glossary.js', 'glossary', glossary, `${glossary.length} plain-English terms.`);

// ---- resources ----
const resources = walk(readJson('resources-raw.json')).categories;
emit('src/data/resources.js', 'resources', resources, `Curated self-custody resources.`);

console.log(`Wrote glossary (${glossary.length} terms), resources (${resources.length} categories).`);
